save reservation
juanii000/Parking-System-Kotlin pull request #5
Opened 2021-08-20 19:02 UTC by juanii000

Save reservation in memory and check that the reservation is correct and not overlapped 

![image (16)](https://user-images.githubusercontent.com/565557/130281157-c1d7acf3-2446-44ce-b7e9-0875f3f87815.png)
![image (15)](https://user-images.githubusercontent.com/565557/130281162-f6cb9999-5f94-4590-a866-c965bcf8c609.png)

![Screenshot from 2021-08-20 15-47-04](https://user-images.githubusercontent.com/565557/130280114-11887ef1-f0b9-43bd-b4d0-5bcfa603c175.png)
![Screenshot from 2021-08-20 15-46-23](https://user-images.githubusercontent.com/565557/130280139-de7855ab-a18d-48ac-ae9a-87432c4e714c.png)
![Screenshot from 2021-08-20 15-47-19](https://user-images.githubusercontent.com/565557/130280092-7c0e0f0f-e274-46ff-a663-90d133a08181.png)

2021-08-20 20:00 UTC, SartiMau requested changes

2021-08-20 20:00 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/presenter/ParkingReservationActivityPresenter.kt
> +                view.showToastParkingReservationSuccess()
I think that you can unify this 3 view methods

2021-08-20 20:00 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/view/ParkingReservationActivityView.kt
> +            datePickerInputParkingReserveEndDate.setText("")
Do not hardcode pls, use contants

2021-08-20 20:00 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/contract/ParkingReservationActivityContract.kt
>  interface ParkingReservationActivityContract {
this should be called ParkingReservationContract

2021-08-20 20:00 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/model/ParkingReservationActivityModel.kt
> +class ParkingReservationActivityModel : ParkingReservationActivityContract.Model {
this should be called  ParkingReservationModel

2021-08-20 20:00 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/presenter/ParkingReservationActivityPresenter.kt
> +class ParkingReservationActivityPresenter(
this should be called  ParkingReservationPresenter

2021-08-20 20:00 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/view/ParkingReservationActivityView.kt
>  class ParkingReservationActivityView(private val binding: ActivityParkingReservationBinding, activity: Activity) :
this should be called  ParkingReservationView

2021-08-20 20:00 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/util/DateUtils.kt
> +        cal.time = sdf.parse(date)!!
do not use !!

2021-08-20 20:00 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/database/ParkingReservationActivityDB.kt
> +object ParkingReservationActivityDB {
this should be called  ParkingReservationDB

2021-08-20 21:04 UTC, nicolbidone requested changes

2021-08-20 21:04 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/database/ParkingReservationActivityDB.kt
> +    val hashMapParkingReserve: HashMap<Int, MutableList<Reservation>> = HashMap()
please use Map interface for the val, try to avoid depending on implementations

2021-08-20 21:04 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/presenter/ParkingReservationActivityPresenter.kt
> +            if (!model.isOverlapReservation(slot, initialDate, endDate)) {
you can use .not() instead of !

2021-08-20 21:04 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/util/DateUtils.kt
> +        val sdf = SimpleDateFormat(context.getString(R.string.pattern_for_date_format_all), Locale.US)
please avoid single use vars

2021-08-20 21:04 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/view/ParkingReservationActivityView.kt
> +        }
if you repeat con context?.let { Toast... } maybe you should move that logic to a single fun

2021-08-20 21:04 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/presenter/ParkingReservationActivityPresenter.kt
> +        }
instead of nested if its recommended to use when { }

2021-08-20 21:04 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/database/ParkingReservationActivityDB.kt
> +            hashMapParkingReserve[reservation.slot] = mutableListOf(reservation)
Does this need to be mutable?

2021-08-20 21:04 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/model/ParkingReservationActivityModel.kt
> +
remove the useless empty line

2021-08-23 20:04 UTC, SartiMau approved these changes

2021-08-24 12:48 UTC, nicolbidone approved these changes

2021-08-24 12:54 UTC, lucianoeli approved these changes

2021-08-24 12:59 UTC, merged