reservation validations fields
juanii000/Parking-System-Kotlin pull request #6
Opened 2021-08-27 19:05 UTC by juanii000

Making validations for fields on reservation activity

- checking for empty fields and slot under the max capacity of the parking

![Screenshot_1630090983](https://user-images.githubusercontent.com/565557/131176613-e8e822e0-c478-4203-a73d-57363bb99a25.png)
![Screenshot_1630090957](https://user-images.githubusercontent.com/565557/131176620-6ee2ffa7-e716-4ef8-a6c6-19826713cdf7.png)

2021-08-27 19:17 UTC, SartiMau requested changes

2021-08-27 19:17 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/presenter/ParkingReservationPresenter.kt
> +                    model.isOverlapReservation(slot, initialDate, endDate).not() && slot < Constants.PARKING_SIZE -> {
check this line, because the logic is not fine. For the success case, you should use an `else ->`

2021-08-27 19:22 UTC, juanii000 commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/presenter/ParkingReservationPresenter.kt
> +                    model.isOverlapReservation(slot, initialDate, endDate).not() && slot < Constants.PARKING_SIZE -> {
Thanks, thats cleaner !

2021-08-27 19:32 UTC, SartiMau approved these changes

2021-08-27 19:38 UTC, lucianoeli approved these changes

2021-08-27 19:43 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/view/ParkingReservationView.kt
> +        }
don´t you have already an extension function for this?

2021-08-30 22:19 UTC, juanii000 commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/view/ParkingReservationView.kt
> +        }
thank you :D

2021-08-31 12:23 UTC, SartiMau requested changes
approved after Mauro's comments

2021-08-31 12:35 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/view/ParkingReservationView.kt
> +        }
there's no need to use let here

2021-09-09 20:11 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/ParkingReservationActivity.kt
> +        presenter.initializeParkingSpace(parkingSize)
initialize should be called on the presenter inside the in { .. } block

2021-09-09 20:11 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/contract/ParkingReservationContract.kt
> +        fun showToastParkingReservation(message: MsgToShow, extraArgument: Int = 0)
please avoid default values on interfaces

2021-09-10 19:53 UTC, nicolbidone approved these changes

2021-09-10 20:30 UTC, SartiMau requested changes

2021-09-10 20:30 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/ParkingReservationActivity.kt
> +            parkingSize
please pass this parameter in a presenter.init(parkingSize) method, not in the constructor

2021-09-10 20:30 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/presenter/ParkingReservationPresenter.kt
> +                        view.cancelActivity()
you should unify this line and the line before

2021-09-10 20:30 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/mvp/view/ParkingReservationView.kt
> +    override fun showToastParkingReservation(message: MsgToShow) {
this logic should be in the presenter.. and the presenter call each correspondent view method

2021-09-28 13:45 UTC, SartiMau requested changes

2021-09-28 13:45 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/ParkingReservationActivity.kt
>      companion object {
please put the companion object at the end of the class

2021-09-28 13:45 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem_kotlin/ParkingReservationActivity.kt
> +        val parkingSize: Int = intent.getIntExtra(EXTRA_PARKING_SIZE,PARKING_SIZE_DEFAULT)
as you are using this variable only in the presenter's call please delete the variable

        presenter.initializeParkingSpace(intent.getIntExtra(EXTRA_PARKING_SIZE,PARKING_SIZE_DEFAULT))

2021-09-28 14:10 UTC, juanii000 commented on app/src/main/java/com/example/parkingsystem_kotlin/ParkingReservationActivity.kt
> +        val parkingSize: Int = intent.getIntExtra(EXTRA_PARKING_SIZE,PARKING_SIZE_DEFAULT)
ok !

2021-09-28 14:10 UTC, juanii000 commented on app/src/main/java/com/example/parkingsystem_kotlin/ParkingReservationActivity.kt
>      companion object {
Done !

2021-09-29 14:00 UTC, SartiMau approved these changes

2021-09-29 14:18 UTC, merged